### ISSUE TITLE
backend/Favorites 

### ISSUE THREAD

**Issue by kimbencinas** [Bay-Valley-Tech-Code-Academy/RuralEats#87]
![image](https://github.com/user-attachments/assets/430b912d-d880-4201-945c-b71253fba509)
I get this issue when i click the heart button on the vendor page.

so the issue is in the route.js file for favorites
--> the HTTP POST method is the problem i think

**Comment by jm2601** [comment]
The error you're encountering (500 Internal Server Error) during the `POST` request to `/api/favorites` seems to be related to the `POST` handler in the `route.js` file.

### **Potential Issues in the `route.js` file:**
1. **Connection to the PostgreSQL Database:**
   - The `pool` object for connecting to the PostgreSQL database may not be initialized correctly in the `POST` handler. Ensure that the `Pool` from `pg` is properly initialized before using it.

2. **Inserting to the `Favorites` Table:**
   - The `restaurant_id` or `user_id` might not be valid or might be missing in the request payload, leading to the failure of the `INSERT` operation.

3. **Error Handling:**
   - There is no detailed error logging, so the actual issue is hidden. You should log the error properly to understand what went wrong.

### **Fixing the Issue:**

1. **Ensure Database Pool Initialization:**
   In the `route.js` file, make sure the `pool` is initialized correctly. Here’s an example of proper initialization:

   ```js
   import { Pool } from 'pg';

   const pool = new Pool({
     user: 'your_db_user',
     host: 'your_db_host',
     database: 'your_db_name',
     password: 'your_db_password',
     port: 5432,  // Default PostgreSQL port
   });
   ```

   Make sure this `pool` initialization is done before any queries are run.

2. **Enhanced Error Logging:**
   Modify the error logging to give you more insights into what's going wrong. For example, change the error catch block to:

   ```js
   export async function POST(req) {
     const { user_id, restaurant_id } = await req.json();

     const query = `
         INSERT INTO Favorites(user_id, restaurant_id)
         VALUES ($1, $2)
         ON CONFLICT DO NOTHING;
     `;

     try {
       await pool.query(query, [user_id, restaurant_id]);
       return new Response('Favorited', { status: 200 });
     } catch (error) {
       console.error('Error favoriting restaurant:', error.message);  // Log the specific error message
       return new Response('Error favoriting restaurant', { status: 500 });
     }
   }
   ```

3. **Verify Data Types and Payload:**
   Make sure that the request body includes `user_id` and `restaurant_id` and that they are correctly formatted. If the IDs are missing, the query will fail.

4. **Check if the Database Table Exists:**
   Confirm that the `Favorites` table exists in your database schema and that it has the appropriate columns (`user_id`, `restaurant_id`).

5. **Debugging the Payload:**
   You can log the payload received in the `POST` handler to confirm that the data is correct:

   ```js
   export async function POST(req) {
     try {
       const { user_id, restaurant_id } = await req.json();
       console.log("Received Payload:", { user_id, restaurant_id });  // Log the payload for debugging

       const query = `
           INSERT INTO Favorites(user_id, restaurant_id)
           VALUES ($1, $2)
           ON CONFLICT DO NOTHING;
       `;

       await pool.query(query, [user_id, restaurant_id]);
       return new Response('Favorited', { status: 200 });
     } catch (error) {
       console.error('Error favoriting restaurant:', error.message);
       return new Response('Error', { status: 500 });
     }
   }
   ```

### **Next Steps:**
1. **Ensure the PostgreSQL connection (`pool`) is initialized correctly in the `route.js` file.**
2. **Enhance the error logging to capture the actual issue.**
3. **Check the request payload to make sure `user_id` and `restaurant_id` are being sent and logged correctly.**

After making these changes, try again and see what specific error message is returned. This should help you pinpoint the exact issue. If the error persists, the detailed log will give you more insights. Let me know if you need further assistance!
